# Generated by Django 4.1.7 on 2023-03-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.PositiveIntegerField(verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='TradeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Factory', 'Завод'), ('Retail', 'Розничная сеть'), ('Seller', 'Индивидуальный предприниматель')], max_length=50, verbose_name='уровень иерархии')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('debt', models.FloatField(blank=True, null=True, verbose_name='Задолженность перед поставщиком')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronics.contact', verbose_name='Контакт')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronics.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronics.tradenetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Торговая сеть',
                'verbose_name_plural': 'Торговые сети',
            },
        ),
    ]
